name: Deploy to GitHub page nathanjent.github.io
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v1

      - name: Checkout source branch
        uses: actions/checkout@v1
        with:
          ref: source

      - name: Download Cobalt Release
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cobalt-org/cobalt.rs
          tag: 'v0.15.6'
          file: cobalt-v0.15.6-x86_64-unknown-linux-gnu.tar.gz

      - name: Extract Cobalt Binary
        run: |
          tar -xzf cobalt-v0.15.6-x86_64-unknown-linux-gnu.tar.gz

      - name: Cobalt deploy to GitHub page
        run: |
          ./cobalt import --branch master --message 'Publish from GitHub Actions ${{ github.event_name }}'

      - name: Push Published Branch
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
