name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cobalt deploy to GitHub page
        uses: saidgeek/cobalt-deploy-gh-pages@v1.0.0
        with:
          branch: master
          githubToken: ${{ secrets.GITHUBTOKEN }}
