name: Deploy to GitHub page nathanjent.github.io
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COBALT_TAG: 'v0.15.6'
      COBALT_DOWNLOAD: cobalt-v0.15.6-x86_64-unknown-linux-gnu.tar.gz
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Cobalt Release
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cobalt-org/cobalt.rs
          tag: $COBALT_TAG
          path: downloads
          file: $COBALT_DOWNLOAD

      - name: Extract Cobalt Binary
        run: |
          tar -xzf $COBALT_DOWNLOAD

      - name: Cobalt deploy to GitHub page
        run: |
          cobalt import --branch master
