name: Deploy to GitHub page nathanjent.github.io
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Cobalt Release
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cobalt-org/cobalt.rs
          tag: 'v0.15.6'
          file: cobalt-v0.15.6-x86_64-unknown-linux-gnu.tar.gz

      - name: Extract Cobalt Binary
        run: |
          tar -xzf cobalt-v0.15.6-x86_64-unknown-linux-gnu.tar.gz

      - name: Checkout source branch
        uses: actions/checkout@v1
        with:
          path: repo
          ref: source

      - name: Cobalt Build
        run: |
          mkdir -p build
          ls
          cd repo
          ./cobalt build --destination ../build

      - name: Checkout master branch
        uses: actions/checkout@v1
        with:
          path: repo

      - name: Clean Previous Build
        run: |
          # Remove items matching file extensions
          find repo \
            -iregex '.*\.\(css\|gif\|html\|ico\|js\|png\|xml\)' \
            -exec rm -r {} +

      - name: Commit build files to master
        run: |
          cp -u -r build/* repo/
          cd repo
          git add *.css *.html *.js *.xml *.png *.gif *.ico
          git commit -m "Publish from GitHub Actions - ${{ github.event_name }}

      - name: Publish to GitHub Pages
        uses: ad-m/github-push-action@master
        with:
          branch: master
          directory: repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
