name: Deploy to GitHub page nathanjent.github.io
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: echo ${{ secrets.GITHUB_TOKEN }}
        name: Token?
      - name: Cobalt deploy to GitHub page
        uses: saidgeek/cobalt-deploy-gh-pages@v1.0.0
        with:
          branch: master
          githubToken: ${{ secrets.GITHUB_TOKEN }}
