name: Deploy to GitHub Pages: nathanjent.github.io

on: 
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v1
        with:
          ref: source

      - name: Download Cobalt Release
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cobalt-org/cobalt.rs
          tag: 'v0.15.6'
          file: cobalt-v0.15.6-x86_64-unknown-linux-gnu.tar.gz

      - name: Extract Cobalt Binary
        run: tar -xzf cobalt-v0.15.6-x86_64-unknown-linux-gnu.tar.gz

      - name: Build
        run: |
          ./cobalt build 
          touch ./_site/.nojekyll

      - name: Deploy
        uses: docker://peaceiris/actions-gh-pages:latest
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./_site
        with:
          emptyCommits: false
          username: actions
          useremail: actions@nathanjent.github.com
