name: Deploy to GitHub page nathanjent.github.io
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Cobalt Release
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cobalt-org/cobalt.rs
          tag: 'v0.15.6'
          path: bin
          file: cobalt-v0.15.6-x86_64-unknown-linux-gnu.tar.gz

      - name: Extract Cobalt Binary
        run: |
          cd bin
          tar -xzf cobalt-v0.15.6-x86_64-unknown-linux-gnu.tar.gz

      - name: Cobalt deploy to GitHub page
        run: |
          ./bin/cobalt import --branch master
